apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-website
  labels:
    app: abc-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abc-website
  template:
    metadata:
      labels:
        app: abc-website
    spec:
      containers:
      - name: abc-website
        image: abc-website:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
