apiVersion: v1
kind: Service
metadata:
  name: abc-website-service
  labels:
    app: abc-website
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  selector:
    app: abc-website
